# Generated by Django 2.2.6 on 2019-12-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(max_length=50)),
                ('serverip', models.CharField(max_length=50)),
                ('serverpassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_serverInfo',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_userInfo',
            },
        ),
    ]
